### ISSUE TITLE
What do parens do in non-extglob?

### ISSUE THREAD

**Issue by phated** [jonschlinkert/is-glob#4]
I can't seem to figure out the purpose for a glob like `./has (parens)/`.  According to the RegExp, that is flagged as a glob but the node-glob readme only references parens with extglob patterns.

This is holding up some work on upgrading node-glob in glob-stream.

**Comment by jonschlinkert** [comment]
I think you're right, parens would only be a glob when it's an extglob pattern. which we already check for.

**Comment by jonschlinkert** [comment]
Actually this isn't a "bug" per se, but I can improve the specificity of the matching. 

> I can't seem to figure out the purpose for a glob like ./has (parens)/.

Patterns like this:

```
abc/(aaa|bbb).js
```

I can make the make the matching more specific so that `|` must be inside the braces too.

**Comment by jonschlinkert** [comment]
Ok, for the following patterns `isGlob` would return **true** (even though `isExtglob` would return **false**):

```js
isGlob('\\?(abc|xyz)/xyz');
isGlob('\\@(abc|xyz)');
isGlob('\\!(abc|xyz)');
isGlob('\\*(abc|xyz)');
isGlob('\\+(abc|xyz)');
```

But for these patterns, `isGlob` and `isExtglob` would both return **false**:

```js
isGlob('?\\(abc|xyz)/xyz');
isGlob('@\\(abc|xyz)');
isGlob('!\\(abc|xyz)');
isGlob('*\\(abc|xyz)');
isGlob('+\\(abc|xyz)');
```

Does this make sense? I believe this should be considered technically correct. However, I wanted to get your thoughts before I push anything up.

**Comment by phated** [comment]
Is that due to the escape sequences?  If so, wouldn't a single forward-slash be the escape character?

**Comment by phated** [comment]
Yeah, I think that's right because if you escape the extglob character, it is no longer an extglob but the parens with `|` in the middle are valid globs.  If you escape the paren (in the 2nd sequence), then it no longer becomes a valid glob because extglob requires the special character followed by the parens.

What happens with:

```js
isGlob('\\?(abc)/xyz');
isGlob('\\@(abc)');
isGlob('\\!(abc)');
isGlob('\\*(abc)');
isGlob('\\+(abc)');
```

**Comment by phated** [comment]
Also, what happens with:

```js
isGlob('?(abc)/xyz');
isGlob('@(abc)');
isGlob('!(abc)');
isGlob('*(abc)');
isGlob('+(abc)');
```
^ should remain valid extglobs, I believe.

**Comment by phated** [comment]
I added a failing test for this in glob-stream: https://github.com/gulpjs/glob-stream/commit/7633c6af1ac240aedc3a41dc8f6aefa91100a3e6

**Comment by jonschlinkert** [comment]
> What happens with:

those would all be `false`. 


> If you escape the paren (in the 2nd sequence), then it no longer becomes a valid glob

agreed, that's how it's implemented now

> should remain valid extglobs, I believe.

agreed. I'll push up what I have now so you can see unit tests - then I'll publish after you review etc.

**Comment by jonschlinkert** [comment]
ok, I updated is-glob and is-extglob:

- [is-glob](https://github.com/jonschlinkert/is-glob/blob/master/index.js) | [tests](https://github.com/jonschlinkert/is-glob/blob/master/index.js)
- [is-extglob](https://github.com/jonschlinkert/is-extglob/blob/master/index.js) | [tests](https://github.com/jonschlinkert/is-extglob/blob/master/test.js)

**Comment by phated** [comment]
Looks like some failing tests.

**Comment by jonschlinkert** [comment]
You're getting failing tests? Or travis? I only pushed up the files necessary for us to review and agree on /patterns

**Comment by phated** [comment]
Travis failures on both.  Reviewing the code now still.

**Comment by jonschlinkert** [comment]
Oh, yeah the reason is-glob will fail is that I'll need to bump `is-extglob` with the proposed changes.

**Comment by phated** [comment]
Some more tests to add to extglob:

```js
isGlob('?(abc/xyz');
isGlob('@(abc');
isGlob('!(abc');
isGlob('*(abc');
isGlob('+(abc');
isGlob('(a|b');
```

I removed the closing paren.  With the current RegExp, I believe these will be true when they should be false.

**Comment by jonschlinkert** [comment]
is-extglob was failing for non-code reasons - I was more focused on the regex but that was distracting, sorry.

**Comment by phated** [comment]
I think extglob looks good with those cases fixed.

**Comment by jonschlinkert** [comment]
I'll do a major and update is-glob (and not published is-glob yet) so we can continue reviewing

**Comment by phated** [comment]
Sounds good.  Is there a way to make is-glob match the braces correctly?

e.g.

```js
isGlob('[abc}'); // returns true (I believe)
```

**Comment by jonschlinkert** [comment]
I was going to comment on this. matching balanced braces/brackets/parens is only easy when there is one set, of one type. For example, `isGlob('{[abc}]');` is invalid and should also be `false`, but it's not trivial to make that determination.  It's equally difficult to determine when patterns are nested.  

IMHO it would be better to leave to a more intelligent matcher/globbing lib. But we could do that here if you think it makes more sense.

**Comment by phated** [comment]
Hard to say.  Hmm

**Comment by phated** [comment]
Can you just do the same regexp pattern as parens?  I think that would be "good enough"

**Comment by jonschlinkert** [comment]
yeah I was just thinking along those lines. I'll do that

**Comment by jonschlinkert** [comment]
@phated ok I pushed up the latest. bumped is-extglob, all tests are passing. I'll publish after you review

**Comment by phated** [comment]
Yeah, I think that looks good.  I visualized the RegExp and 👍  on the tests.  Thanks for digging into this.

**Comment by jonschlinkert** [comment]
@phated btw, on a related note I started refactors of both extglob and micromatch using a better parser/renderer (they even create source maps. I don't know where they would be used, but they come for free). 

You can see the extglob branch here: https://github.com/jonschlinkert/extglob/pull/3/files#diff-3fab227e34d65fe9bb2d6ea53eec41cfR20. 

I noted this in the pr, but since there is a lot of noise, with the refactor extglob passes 238 of 240 bash 4.3 unit tests, of which minimatch fails 90. The two failing tests are debatable - I think my code is correct, but bash disagrees. plus it's considerably faster. Improvements for micromatch will be similar.

**Comment by tunnckoCore** [comment]
@jonschlinkert oooh, is there `micromatch` refactor branch really? I'm excited to see it, I already reviewed the refactored extglob and it's crazy.

**Comment by jonschlinkert** [comment]
lol thanks @tunnckoCore. It's almost ready to push up. I only haven't b/c I had to create a new lexer/parser for https://github.com/jonschlinkert/snapdragon for it to work - and I haven't had a chance to move that code over. 

the approach is faster and more accurate, but given that it's a completely different approach I'll want to test the heck out of it before it's actually published and bumped (currently it has 4k unit tests, but I'd like to do a lot more by auto-generating the patterns).

**Comment by phated** [comment]
@jonschlinkert thanks and that's awesome about the refactor!  Hitting almost all the bash tests is a great accomplishment.  Are you opposed to publishing it as a major with the `next` tag so people can start using it and putting it through the paces?

**Comment by jonschlinkert** [comment]
> Are you opposed to publishing it as a major with the next tag so people can start using it and putting it through the paces?

no problem, using the `next` tag is a great idea. I'm not sure when I'll get around to it but I'll ping you.

**Comment by jonschlinkert** [comment]
ok, just for fun, what do you think the result should be for each of these?

```js
extglob.isMatch('foob', '!(foo)b*');
extglob.isMatch('foobb' '!(foo)b*');
```

**Comment by tunnckoCore** [comment]
haha, `false` for both? because the star is for  `0 or more`? hm.

**Comment by jonschlinkert** [comment]
> false for both?

that's my answer too
