### ISSUE TITLE
Support escape characters

### ISSUE THREAD

**Issue by phated** [jonschlinkert/is-glob#5]
It seems that node-glob supports escaping special characters but this library doesn't.

**Comment by jonschlinkert** [comment]
good idea, I'll do this and https://github.com/jonschlinkert/is-glob/issues/4 today.

**Comment by phated** [comment]
Awesome, much appreciated.

**Comment by jonschlinkert** [comment]
No problem, thanks for creating the issue. Let me know if you think of anything else
