### ISSUE TITLE
Returns True when passed a windows path that includes ().

### ISSUE THREAD

**Issue by Jorenm** [jonschlinkert/is-glob#6]
For example, anything under C:/Program Files (x86)/

**Comment by jonschlinkert** [comment]
I just tested the pattern and it returns `false`. It should only return true for parentheses when preceded by an extglob character, or when the pattern is a regex `or` (e.g. `(a|b)`)

**Comment by Jorenm** [comment]
My apologies. It looks like the version being required (by whatever package is requiring it) is only version 2.0 and is way more simplistic in its tests.

**Comment by jonschlinkert** [comment]
no worries, thanks for the follow up
